Add models and api views
aylar23/SocialMediaApp pull request #1
Opened 2023-07-19 12:13 UTC by aylar23

2023-08-01 23:02 UTC, PermanAtayev requested changes

2023-08-01 23:02 UTC, PermanAtayev commented on socium/user/urls.py
> +    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
User login edenden soňra ol user-e tokeni berseň, soňam hemme login gerek bolan endpointlerde request bilen gelen token-yň dogrulygyny ýa-da dälligini barlasaň has gowy bolar. 

Şu ýerde gowja makala bar eken: https://levelup.gitconnected.com/how-to-secure-your-rest-api-using-jwt-a923ba4a497e

2023-08-01 23:02 UTC, PermanAtayev commented on socium/user/urls.py
> +    path('api/request_decline/<request_id>', DeclineFollowRequestApiView.as_view(), name='request-decline'),
Rest api-de endpointerde işlik ulanmak maslahat berilenok. Her endpoint bir resource bilen baglanyşykly bolmaly

Follow we unfollow-y rest bilen şular ýaly gurup bilersiň: https://softwareengineering.stackexchange.com/questions/339751/options-for-the-restful-approach-for-follow-and-unfollowing

2023-08-12 18:03 UTC, aylar23 commented on socium/user/urls.py
> +    path('token/verify/', TokenVerifyView.as_view(), name='token_verify'),
Barlayana:
class FollowRequestsApiView(GenericAPIView):
    permission_classes = [IsAuthenticated]  user authenticatedmi dal-mi sony  barlayar

2023-08-12 18:11 UTC, aylar23 commented on socium/user/permissions.py
> +        return obj == request.user
bardaki obj user, meselem user profile-ini uytgetjek bolsa dine ozuninkisini uytgedip biler yaly, basgasynynky bolsa dine safe method-leri ulanyp bilyar.

2023-08-12 18:11 UTC, aylar23 commented on socium/user/models.py
> +    updated = models.DateTimeField(auto_now=True)
bir zatlar etjek boldum, ayyrmak yadymdan cykypdyr

2023-08-12 18:11 UTC, aylar23 commented on socium/user/urls.py
> +    path('api/request_decline/<request_id>', DeclineFollowRequestApiView.as_view(), name='request-decline'),
Done

2023-08-12 18:16 UTC, aylar23 commented on socium/user/models.py
> +        self.receiver.following.add(self.sender)
Hawa, duzetdim

2023-08-19 08:55 UTC, merged